#!/bin/bash

# example .ascrrc:

# SERVER=tschuy@ash.osuosl.org
# DIRECTORY=~/public_html/screenshots/
# URL=https://ash.osuosl.org/~tschuy/screenshots

source ~/.ascrrc  > /dev/null 2>&1

if [ -z "$1" ]; then
    NAME="$(date '+%d_%m_%Y_%H%M%S')"
else
    if [ ${1: -4} == ".png" ]; then
        NAME=${1:0:-4}
    else
        NAME=$1
    fi
fi

if [ -x /usr/sbin/screencapture ]; then
    /usr/sbin/screencapture -x /tmp/$NAME.png
else
    import /tmp/$NAME.png
fi
scp /tmp/$NAME.png $SERVER:$DIRECTORY > /dev/null 2>&1

if [ $? -eq 1 ]; then
    rm /tmp/$NAME.png
    echo "Unable to upload screenshot. Verify remote destination exists and that you have permissions to access it."
    exit 1
fi
	
rm /tmp/$NAME.png

echo "$URL/$NAME.png"
if hash xclip 2>/dev/null; then
    echo "$URL/$NAME.png" | xclip -selection c
fi
